// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc330.Beachbot2013Java.commands;
import edu.wpi.first.wpilibj.command.AutoSpreadsheetCommand;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc330.Beachbot2013Java.Robot;
/**
 * Drive the robot a specified distance using encoders and PID only. Finish when
 * the robot is with the specified {@link #setParam2(double) tolerance}. 
 * The {@link #setParam1(double) distance} is relative to the
 * Robot's starting position. DriveEncoder should not be used if the robot has turned. 
 * {@link DriveEncoderRel} should be used in this case.
 * 
 * For example, to drive 10 feet forward, set distance to 120 (inches).
 * 3 inches is a reasonable tolerance for normal movements. If a smaller
 * tolerance is used, the robot may not ever reach the tolerance, and the 
 * {@link #setTimeout(double) timeout} may be reached.
 * 
 * @see DriveEncoderGyro
 * @see DriveEncoderRel
 * 
 * @author Joe
 */
public class  DriveEncoder extends Command implements AutoSpreadsheetCommand {
    double leftDistance, rightDistance, tolerance;
    boolean stopAtEnd = false;
    
    public DriveEncoder()
    {
        this(0,0,0,false);
    }
    
    public DriveEncoder(double distance) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        this(distance, 0, 0, false);
    }
    
    public DriveEncoder(double distance, double tolerance)
    {
        this(distance, tolerance, 0, false);
    }
    
    public DriveEncoder(double distance, double tolerance, double timeout, boolean stopAtEnd)
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.chassis);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        this.leftDistance = distance;
        this.rightDistance = distance;
        this.tolerance = tolerance;
        setTimeout(timeout);
        this.stopAtEnd = stopAtEnd;
    }
    
    // Called just before this Command runs the first time
    protected void initialize() {
        Robot.chassis.gyroPIDLow.disable();
        Robot.chassis.gyroPIDHigh.disable();
        if (!Robot.chassis.getShiftState())
        {
            Robot.chassis.leftDrivePIDLow.setSetpoint(leftDistance);
            Robot.chassis.rightDrivePIDLow.setSetpoint(rightDistance);
            Robot.chassis.leftDrivePIDLow.enable();
            Robot.chassis.rightDrivePIDLow.enable();
            Robot.chassis.leftDrivePIDLow.setAbsoluteTolerance(tolerance);
            Robot.chassis.rightDrivePIDLow.setAbsoluteTolerance(tolerance);
        }
        else
        {
            Robot.chassis.leftDrivePIDHigh.setSetpoint(leftDistance);
            Robot.chassis.rightDrivePIDHigh.setSetpoint(rightDistance);
            Robot.chassis.leftDrivePIDHigh.enable();
            Robot.chassis.rightDrivePIDHigh.enable(); 
            Robot.chassis.leftDrivePIDHigh.setAbsoluteTolerance(tolerance);
            Robot.chassis.rightDrivePIDHigh.setAbsoluteTolerance(tolerance);
        }
        //Robot.chassis.leftDrivePID.disable();
        //Robot.chassis.rightDrivePID.disable();
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        if (!Robot.chassis.getShiftState())
        {
            if (Robot.chassis.leftDrivePIDLow.onTarget() || Robot.chassis.rightDrivePIDLow.onTarget() || isTimedOut())
            {
                return true;            
            }
        }
        else if (Robot.chassis.leftDrivePIDHigh.onTarget() || Robot.chassis.rightDrivePIDHigh.onTarget() || isTimedOut())
        {
                return true;            
        }
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
        if (stopAtEnd)
        {
            Robot.chassis.stopDrive();
        }
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        stopAtEnd = true;
        end();
    }
    
        /**
     * The first parameter in the AutoSpreadsheet, distance. 
     * The distance to drive in inches from the starting point of the robot. 
     * To drive 10 feet forward, set distance to 120 (inches). To drive backwards
     * set the distance negative.
     * @param distance distance to drive in inches
     */
    public void setParam1(double distance) {
        this.leftDistance = distance;
        this.rightDistance = distance;
    }
    /**
     * The second parameter in the AutoSpreadsheet, tolerance. 
     * The tolerance in inches for how close to be to the distance before stopping.
     * 3 inches is a reasonable tolerance for normal movements. If a smaller
     * tolerance is used, the robot may not ever reach the tolerance, and the 
     * {@link #setTimeout(double) timeout} may be reached.
     * @param tolerance in inches
     * @see edu.wpi.first.wpilibj.PIDController#setAbsoluteTolerance
     */
    public void setParam2(double tolerance) {
        this.tolerance = tolerance;
    }
    /**
     * Not Used
     * @param param3 
     */
    public void setParam3(double param3) {
    }
    /**
     * Stop the drive train at the end of the command
     * @param stopAtEnd if true, stop the drive train at the end of the command.
     *  If false, keep the PID running at the end so the robot keeps its position
     */
    public void setStopAtEnd(boolean stopAtEnd) {
        this.stopAtEnd = stopAtEnd;
    }
    public Command copy() {
        return new DriveEncoder();
    }
}
