// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc330.Beachbot2013Java.commands;
import edu.wpi.first.wpilibj.command.AutoSpreadsheetCommand;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc330.Beachbot2013Java.Robot;
/*
 * $Log: DriveEncoderGyroRamp.java,v $
 * Revision 1.1  2013-02-16 06:08:20  jross
 * Copy drive commands from beachbot2012robotbuilder
 *
 * Revision 1.11  2013-02-15 06:19:04  jross
 * fix extensions of Drive Encoder
 *
 * Revision 1.10  2013-02-12 05:57:45  jross
 * make absolute again, but with different left and right so that it can be used by relative functions
 *
 * Revision 1.9  2013-02-11 06:53:10  jross
 * call PIDDrive from robot. make relative
 *
 * Revision 1.8  2013-02-10 21:21:29  jross
 * add high gear PID for gyro
 *
 * Revision 1.7  2013-02-10 20:41:24  jross
 * fix high gear PID for left and right drive
 *
 * Revision 1.6  2013-02-09 05:26:33  jross
 * use chassis.get angle rather then RobotMap. Fix spelling of getLeftDistance
 *
 * Revision 1.5  2013-02-09 04:46:32  jross
 * Add high gear PID for left and right drive
 *
 * Revision 1.4  2013-02-09 01:39:58  jross
 * rename left and right drive PIDs to show they are for low gear.
 *
 * Revision 1.3  2013-02-03 00:00:59  jross
 * Remove print statements for ramp
 *
 * Revision 1.2  2013-02-03 00:00:24  jross
 * Fix copy method
 *
 * Revision 1.1  2013-02-02 23:05:48  echan
 * Added Ramping to the DriveEncoderGyro
 *
 * Revision 1.4  2013-01-18 05:29:25  jross
 * remove name with parameters which conflicts with autospreadsheet
 *
 * Revision 1.3  2013-01-02 04:22:41  jross
 * Whitespace changes from RobotBuilder
 *
 * Revision 1.2  2013-01-02 03:20:36  jross
 * Import code from Beachbot2012JavaBeta Project
 *
 * Revision 1.5  2012-12-09 03:41:13  jross
 * firstRun variable in execute is no longer needed because initialize works
 *
 * Revision 1.4  2012-12-03 03:40:07  jross
 * Convert more commands to AutoSpreadsheetCommand
 *
 * Revision 1.3  2012-11-14 05:05:25  jross
 * use setAbsoluteTolerance
 *
 * Revision 1.2  2012-10-24 05:05:35  jross
 * fix first run bug
 *
 * Revision 1.1.1.1  2012-10-06 21:54:05  jross
 * BeachBot2012 project as of 10/6. To be updated to use new 2013 beta libraries.
 *
 * Revision 1.1  2012-10-02 03:31:36  jross
 * drive a distance maintaining an angle
 *
 * Revision 1.3  2012-09-30 18:57:14  jross
 * Fixed and tested 9/30
 *
 * Revision 1.2  2012-09-30 03:01:25  jross
 * Add timeout and stopAtEnd
 *
 * Revision 1.1  2012-09-21 03:01:46  jross
 * Drive a distance using the encoders
 *
 */
/**
 *
 */
public class  DriveEncoderGyroRamp extends DriveEncoderGyro{
    double maxoutput = 0;
    double maxoutputStep = .02;
    
    public DriveEncoderGyroRamp()
    {
        this(0,0,0,0,true);
    }
     
    public DriveEncoderGyroRamp(double distance, double angle)
    {
        this(distance, 0, angle, 0, true);
    }
    
    public DriveEncoderGyroRamp(double distance, double tolerance, double angle, double timeout, boolean stopAtEnd)
    {
        super(distance, tolerance, angle, timeout, stopAtEnd);
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        maxoutput = maxoutputStep;
        super.initialize();
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        maxoutput = maxoutput + maxoutputStep;
        if (maxoutput > .8)
        {
            maxoutput = .8;
        }
        if (!Robot.chassis.getShiftState())
        {
            Robot.chassis.leftDrivePIDLow.setOutputRange(-maxoutput, maxoutput);
            Robot.chassis.rightDrivePIDLow.setOutputRange(-maxoutput, maxoutput);
        }
        else
        {
            Robot.chassis.leftDrivePIDHigh.setOutputRange(-maxoutput, maxoutput);
            Robot.chassis.rightDrivePIDHigh.setOutputRange(-maxoutput, maxoutput);            
        }
    }
    public Command copy() {
        return new DriveEncoderGyroRamp();
    }
}
