// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc330.Beachbot2013Java.commands;
import edu.wpi.first.wpilibj.command.AutoSpreadsheetCommandGroup;
import edu.wpi.first.wpilibj.command.CommandGroup;
/*
 * $Log: ShootLowCommandGroup.java,v $
 * Revision 1.4  2013-03-17 20:25:33  jross
 * Add bang bang control of the shooter motor
 *
 * Revision 1.3  2013-03-17 18:20:54  jross
 * reverse order of spinning up shooter and moving arm
 *
 * Revision 1.2  2013-03-15 02:51:09  echan
 * added cvs log comments
 *
 */
 
/**
 *
 */
public class ShootLowCommandGroup extends AutoSpreadsheetCommandGroup {
    
    public  ShootLowCommandGroup() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        addSequential(new PickupFrisbeesOff());
        addParallel(new ArmLowShooting());
        addSequential(new ShootLowBangBang());
    }

    public AutoSpreadsheetCommandGroup copy() {
        return new ShootLowCommandGroup();
    }
}
