// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc330.Beachbot2013Java.subsystems;

import org.usfirst.frc330.Beachbot2013Java.RobotMap;
import org.usfirst.frc330.Beachbot2013Java.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc0330.wpilibj.CFA634SPI.Line;
import org.usfirst.frc0330.wpilibj.SmartDashboardLCD;
/*
 * $Log$S
 */

/**
 *
 */
public class LCD extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalOutput mosi = RobotMap.lCDmosi;
    DigitalOutput cs = RobotMap.lCDcs;
    DigitalOutput clk = RobotMap.lCDclk;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public SmartDashboardLCD lcd = null;

    public void addLine(Line row, String variable) {
        lcd.addLine(row, variable);
    }

    public void updateLCD() {
        lcd.updateLCD();
    }
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new UpdateLCD());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public LCD()
    {
        SPIDevice.initBus(clk, mosi, null);
        lcd = new SmartDashboardLCD(cs);
    }
}

