// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc330.Beachbot2013Java.subsystems;
import org.usfirst.frc330.Beachbot2013Java.RobotMap;
import org.usfirst.frc330.Beachbot2013Java.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import java.util.TimerTask;
import org.usfirst.frc330.Beachbot2013Java.Robot;
import org.usfirst.frc330.wpilibj.CFA634SPI;
import org.usfirst.frc330.wpilibj.CFA634SPI.Line;
import org.usfirst.frc330.wpilibj.SmartDashboardLCD;
/*
 * $Log: LCD.java,v $
 * Revision 1.4  2013-02-16 04:54:57  jross
 * rename package to org.usfirst.frc330.wpilibj to match other packages
 *
 * Revision 1.3  2013-02-09 22:57:51  echan
 * Robot Builder removed blank lines
 *
 * Revision 1.2  2013-02-09 02:26:29  jross
 * Add LCD method forwarding
 *S
 */
/**
 *
 */
public class LCD extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalOutput mosi = RobotMap.lCDmosi;
    DigitalOutput cs = RobotMap.lCDcs;
    DigitalOutput clk = RobotMap.lCDclk;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public SmartDashboardLCD lcd = null;
    public void addLine(Line row, String variable) {
        lcd.addLine(row, variable);
    }
    public void updateLCD() {
        lcd.updateLCD();
    }
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    java.util.Timer timer;
    public LCD()
    {
        SPIDevice.initBus(clk, mosi, null);
        lcd = new SmartDashboardLCD(cs);
        SmartDashboard.putNumber("Gyro Angle", 0);
        SmartDashboard.putNumber("Batt Voltage", 0);
        lcd.addLine(CFA634SPI.Line.kUser1, "Batt Voltage");
        lcd.addLine(CFA634SPI.Line.kUser2, "angleToCenter");
        lcd.addLine(CFA634SPI.Line.kUser3, "distanceToCenter");
        lcd.addLine(CFA634SPI.Line.kUser4, "Gyro Angle");
        timer = new java.util.Timer();
        timer.schedule(new UpdateLCDtask(), 250, 250);
    }
        class UpdateLCDtask extends TimerTask {
        public void run() {
            SmartDashboard.putNumber("Batt Voltage", DriverStation.getInstance().getBatteryVoltage());
            SmartDashboard.putNumber("Gyro Angle", RobotMap.chassisGyro.getAngle());
            Robot.lCD.updateLCD();
        }
    }
}
