// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc330.Beachbot2014Java.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc330.Beachbot2014Java.Robot;
import org.usfirst.frc330.Beachbot2014Java.subsystems.Chassis;
/**
 *
 */

public class  DriveDistanceAccel extends DriveDistance{
    double maxoutput = 0;
    double maxoutputStepHigh = Robot.chassis.getDriveRampStepHigh();
    double maxoutputStepLow = Robot.chassis.getDriveRampStepLow();
    
    public DriveDistanceAccel(double distance) {
        this(distance, 0, 0, true);
    }
    
    public DriveDistanceAccel(double distance, double tolerance, double timeout, boolean stopAtEnd) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        super(distance, tolerance, timeout, stopAtEnd);
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        if (Robot.chassis.getShiftState())
        {
            maxoutput = maxoutputStepHigh;
        }
        else
        {
            maxoutput = maxoutputStepLow;
        }
        
        super.initialize();
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        if (Robot.chassis.getShiftState())
        {
            maxoutput = maxoutput + maxoutputStepHigh;
        }
        else
        {
            maxoutput = maxoutput + maxoutputStepLow;
        }
        if (maxoutput > .8)
        {
            maxoutput = .8;
        }
        Robot.chassis.leftDrivePID.setOutputRange(-maxoutput, maxoutput);
        Robot.chassis.rightDrivePID.setOutputRange(-maxoutput, maxoutput);
    }
    
    public Command copy() {
        return new DriveDistanceAccel(0);
    }
}
