// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc330.Beachbot2014Java.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc330.Beachbot2014Java.Robot;
/**
 *
 */
public class  OppositeArmBumperPosition extends Command {
    public OppositeArmBumperPosition() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.arm);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    double timer;
    
    // Called just before this Command runs the first time
    protected void initialize() {
        Robot.arm.disable();
        Robot.wings.setWingsOpen();
        timer = Robot.wings.getWingOpenTime() + Robot.arm.armWaitWings();
        Robot.arm.setArmSetPointBackBumper();
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        if (Robot.wings.areWingsOpen() && Timer.getFPGATimestamp() > timer) {
            if (!Robot.arm.isEnable())
                Robot.arm.enable();
        }
        else if (Robot.arm.isEnable())
            Robot.arm.disable();
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return Robot.arm.onTarget();
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
