// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc330.Beachbot2014Java.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc330.Beachbot2014Java.Robot;
/**
 *
 */
public class  RedGreenBlueLEDs extends Command {
    double LEDTimer;
    boolean red;
    boolean blue;
    boolean green;
    
    public RedGreenBlueLEDs() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.lEDs);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        setRunWhenDisabled(true);
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        blue = true;
        LEDTimer = Timer.getFPGATimestamp();
        System.out.println("LED Loop Initializing");
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        if (blue && Timer.getFPGATimestamp() > LEDTimer + 1) {
            Robot.lEDs.setRed();
            red = true;
            blue = false;
            green = false;
            LEDTimer = Timer.getFPGATimestamp();
            System.out.println("LED Loop Set Red");
        }
        if (red && Timer.getFPGATimestamp() > LEDTimer + 1) {
            Robot.lEDs.setGreen();
            green = true;
            red = false;
            blue = false;
            LEDTimer = Timer.getFPGATimestamp();
            System.out.println("LED Loop Set Green");
        }
        if (green && Timer.getFPGATimestamp() > LEDTimer + 1) {
            Robot.lEDs.setBlue();
            blue = true;
            red = false;
            green = false;
            LEDTimer = Timer.getFPGATimestamp();
            System.out.println("LED Loop Set Blue");
        }
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        System.out.println("LED Loop Interrupted");
    }
}
